### ISSUE TITLE
ImportError:~/DCNv2/_ext/dcn_v2/_dcn_v2.so: undefined symbol: THCudaTensor__nDimension

### ISSUE THREAD

**Issue by zccoder** [CharlesShang/DCNv2#1]
After I have runned '. mask.sh', and then 'python test.py', This error produced.Why?

**Comment by LZP4GitHub** [comment]
I also meet the  error when I run ‘test.py’, in line 113
https://github.com/CharlesShang/DCNv2/blob/99a8293352df1840cc7c7f1ab8945286a7a8d57f/test.py#L113
the error is
`TypeError: initializer for ctype 'struct THCudaTensor *' must be a pointer to same type, not cdata 'struct THCudaDoubleTensor *'`

**Comment by CharlesShang** [comment]
@zccoder 
This is built on torch 0.4.1
run
```
import torch
torch.__version__
# '0.4.1'
```
to check

**Comment by CharlesShang** [comment]
@LZP4GitHub 
you can swith between double and float in dcn_v2_func.py manually
```
from _ext import dcn_v2 as _backend
# from _ext import dcn_v2_double as _backend
```
Double precision is **only** for gradient check, it's not recommended because it's poorly optimized by Nvidia.

**Comment by everjesse** [comment]
I've met the same issue. I found there are typos in src/dcn_v2_cuda.c.
To change **THCudaTensor__nDimension** to **THCudaTensor_nDimension** may resolve this.

**Comment by CharlesShang** [comment]
@everjesse Thanks for reporting this. That's weird, I'll check whether both function names exist.

**Comment by CharlesShang** [comment]
THCudaTensor_nDimension corresponds to dim(), THCudaTensor__nDimension to _dim(). 
dim() is the *new* ATen API that supports zero dimension, thus it’s recommended. 
I’ll change it later.  @everjesse

**Comment by everjesse** [comment]
Thanks for fixing this! 
Your update with PyTorch 1.0 is pretty cool, and it works well! @CharlesShang

**Comment by CharlesShang** [comment]
Good to know it, thanks! @everjesse
