### ISSUE TITLE
fatal error: cusparse.h: No such file or directory

### ISSUE THREAD

**Issue by butyuhao** [CharlesShang/DCNv2#11]
Hello. I run your code with pytorch1.0.1. When I run ./make.sh, it tells me fatal error: cusparse.h: No such file or directory. I think I've correctly installed the pytorch. Is there anyone encountered the same problem?

**Comment by CharlesShang** [comment]
`cusparse.h` should be in cuda-xx/include` folder. 
might be you don't correctly configure your cuda path, using `locate cusparse.h` to find it.
