### ISSUE TITLE
What is deformable group?

### ISSUE THREAD

**Issue by Simpatech-app** [CharlesShang/DCNv2#12]
Hello 
Thanks for your great implementation.
I have a question regarding the deformable group variable ? 
I am not sure what exactly is useful for? 
I appreciate your guide. Thanks

**Comment by CharlesShang** [comment]
I think a deformable group is just like convolotion group. Same topology, same intuition.

**Comment by yangle15** [comment]
Deformable group is not convolutional group!!

See https://github.com/msracver/Deformable-ConvNets/issues/268 for the original author's explanation.
