### ISSUE TITLE
Segmentation Fault when testing

### ISSUE THREAD

**Issue by SCoulY** [CharlesShang/DCNv2#17]
I successfully built up the dependencies but failed in test phase, anyone knows what caused this?
`Installed /home/yuankunhao/DCNv2

Processing dependencies for DCNv2==0.1

Finished processing dependencies for DCNv2==0.1

(yuankunhao) [root@localhost DCNv2]# python test.py 

Segmentation fault

(yuankunhao) [root@localhost DCNv2]# python test.py 

Segmentation fault
`

**Comment by guanlinting** [comment]
get the same result when run test.py, my gpu driver version is: 384.130, cuda version is V9.2.148, any suggestion?

**Comment by mangdian** [comment]
get the same problem

**Comment by mangdian** [comment]
@SCoulY  @guanlinting Have you solved the problem?

**Comment by guanlinting** [comment]
@mangdian noop

**Comment by linzhi123** [comment]
get the same problem

**Comment by linzhi123** [comment]
@SCoulY @guanlinting @mangdian Have you solved the problem?

**Comment by ruinianxu** [comment]
@linzhi123  @SCoulY  @guanlinting  @mangdian You will need gcc's version larger than 4.9 to compile the extension.

**Comment by superxudou** [comment]
Must GCC be version 5.0 or higher? I also get segment default. My GCC is 4.8

**Comment by SCoulY** [comment]
> Must GCC be version 5.0 or higher? I also get segment default. My GCC is 4.8

it seems so, i successfully compiled it under gcc 7.3.0.

**Comment by TangShengqin** [comment]
when gcc is 4.8.0, i meet "Segmentation Fault" error, and i solve this problem when i change gcc version to 5.8.0,

**Comment by ZhangYuef** [comment]
Meet this problem using `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`
