### ISSUE TITLE
fatal error: cuda_runtime_api.h: No such file or directory

### ISSUE THREAD

**Issue by murdockhou** [CharlesShang/DCNv2#20]
python=3.6
pytorch=1.0.0
cuda=10.0

when running `make.sh`, give this error message:
![image](https://user-images.githubusercontent.com/18358653/57927662-47dab100-78e1-11e9-9d8d-1b34e90d657c.png)

**Comment by joyyang1215** [comment]
same issue

**Comment by ZhWL123456** [comment]
Add a line in the 'set_up.py':
sources = [os.path.join(extensions_dir, s) for s in sources]
include_dirs = [extensions_dir]
include_dirs.append('/usr/local/cuda/include') #I added this line
ext_modules = [
extension(
"_ext",
sources,
include_dirs=include_dirs,
define_macros=define_macros,
extra_compile_args=extra_compile_args,
)
]

**Comment by murdockhou** [comment]
@ZhWL123456 Solved this problem, thanks~
