### ISSUE TITLE
Win10下编译出现问题

### ISSUE THREAD

**Issue by anymyb** [CharlesShang/DCNv2#28]
正在创建库 build\temp.win-amd64-3.7\Release\Users\anymy\Desktop\DCNv2-master\src\_ext.cp37-win_amd64.lib 和对象 build\temp.win-amd64-3.7\Release\Users\anymy\Desktop\DCNv2-master\src\_ext.cp37-win_amd64.exp
dcn_v2_cuda.obj : error LNK2001: 无法解析的外部符号 "struct THCState * state" (?state@@3PEAUTHCState@@EA)
build\lib.win-amd64-3.7\_ext.cp37-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

**Comment by Wslsdx** [comment]
@anymyb  我也遇到了同样的问题，请问你解决了没？

**Comment by Wslsdx** [comment]
@anymyb    在关闭的问题里面已经有解决了

**Comment by anymyb** [comment]
> @anymyb 在关闭的问题里面已经有解决了

**Comment by anymyb** [comment]
已经有解决了

**Comment by anymyb** [comment]
必须要修改 dcn_v2_cuda.cu 里一句代码：
//extern THCState *state;                            THCState *state = at::globalContext().lazyInitCUDA();   // Modified





------------------ 原始邮件 ------------------
发件人: "Wslsdx"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午3:51
收件人: "CharlesShang/DCNv2"<DCNv2@noreply.github.com>;
抄送: "无聊院长"<1602592035@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CharlesShang/DCNv2] Win10下编译出现问题 (#28)




@anymyb  我也遇到了同样的问题，请问你解决了没？
