### ISSUE TITLE
DCNv2/src/cuda/dcn_v2_cuda.cu(107): error: identifier "THCState_getCurrentStream" is undefined

### ISSUE THREAD

**Issue by lucasjinreal** [CharlesShang/DCNv2#57]
torch 1.5 

```
DCNv2/src/cuda/dcn_v2_cuda.cu(107): error: identifier "THCState_getCurrentStream" is undefined

```

**Comment by huaze555** [comment]
@jinfagang i have the same problem, have you solved this problem?

**Comment by lucasjinreal** [comment]
Using my fork: https://github.com/jinfagang/DCNv2_latest

**Comment by huaze555** [comment]
@jinfagang It works! Thank you very much!

**Comment by FranciscoReveriano** [comment]
Unfortunately it did not work for me

**Comment by FranciscoReveriano** [comment]
@jinfagang  What alterations did you make in your repo? 
I am trying to figure out how to solve this problem.

**Comment by lucasjinreal** [comment]
Upgrade torch 1.5

**Comment by FranciscoReveriano** [comment]
I tried that. I still end up getting that same problem. Which CUDA/gcc version are you using? 
I am trying to avoid messing with the CUDA  installation.

**Comment by lucasjinreal** [comment]
I only got this with torch 1.4 or > 1.4 Using my fork I solved my problem.

**Comment by Asuna88** [comment]
how about try this:
https://blog.csdn.net/a563562675/article/details/107849193
---------
应该是pytorch版本的问题，有网友将pytorch切换到1.4便解决了。现在官方给出了解决方法，可见DCNv2-git。
简单来说就是将src/cuda/dcn_v2_cuda.cu 文件中的THCState_getCurrentStream(state)都替换为c10::cuda::getCurrentCUDAStream()。
