### ISSUE TITLE
Error Pytorch 1.7

### ISSUE THREAD

**Issue by khiratsuka** [CharlesShang/DCNv2#89]
OS : Ubuntu 20.04 LTS
GPU : Geforce RTX 3090
CUDA : v11.1.1
cuDNN : v8.0.4
Pytorch v1.7

‘THFloatBlas_gemv’ was not declared in this scope; ‘THFloatBlas_gemm’ was not declared in this scope;
I have these errors.
I need your help about it.

**Comment by tyutlk** [comment]
same issue

OS : Ubuntu 18.04 LTS
GPU : Geforce TITAN RTX
CUDA : v10.1
Pytorch v1.7

**Comment by khiratsuka** [comment]
same issue, closed.
https://github.com/CharlesShang/DCNv2/issues/90
